### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_03#8]
## Descrição
Criar Gofs Criacionais do projeto com [Builder](https://aprender3.unb.br/pluginfile.php/2928953/mod_page/content/1/Arquitetura%20e%20Desenho%20de%20Software%20-%20Aula%20GoFs%20Criacionais%20-%20Profa.%20Milene.pdf).

## Tarefas
- [x] Documentar em 3.1.3.
- [x] Seguir [template de documentação](https://github.com/UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_03/blob/main/.github/TEMPLATE_DOC.md)
- [x] Colocar na issue a gravação da realização.

## Critérios de aceitação
- [x] Titulo enumerado
- [x] Ortografia correta
- [x] Link nos textos para as referencias 
- [x] Bibliografia está presente e segue o padrão ABNT
- [x] Versionamento padronizado
- [x] Títulos e citações em figuras, tabelas e videos seguem o padão ANBT
- [x] Citações diferem autores de fonte

## Observações

**Comment by claudiohsc** [comment]
Abaixo a primeira versão do Diagrama do Padrão Criacional Builder:


![Padrão_Criacional_Builder drawio](https://github.com/user-attachments/assets/145a3fb4-b960-4374-964d-815bdcf7e1b7)

**Comment by claudiohsc** [comment]
Reunião da gravação: [Link](https://www.youtube.com/watch?v=9wh78V0ap3U)
